export enum PaintScreenEventType {
	POINTER_DOWN = "pointer-down",
	POINTER_UP = "pointer-up",
	POINTER_MOVE = "pointer-move",
}

export type AnyCursorEvent = MouseEvent | TouchEvent | PointerEvent

/**
 * Any event, which is generated by SceneRenderer or it's parent - container having the whole screen.
 */
export type PaintScreenEvent = {
	type:
		| PaintScreenEventType.POINTER_DOWN
		| PaintScreenEventType.POINTER_MOVE
		| PaintScreenEventType.POINTER_UP
	event: AnyCursorEvent
}
